### PR TITLE
Aview ai pages

### LINKED ISSUE #1: Aview AI pages
how is this the first issue on this repo lmao. @d-huliu here is the [figma link](https://www.figma.com/design/PMfG3eyLRvDwQ2iG2QXUmK?node-id=3090-18488#886757031). let me know if you have further questions

### PR DESCRIPTION
**Pull request by d-huliu**
faulty formatting, subtitle editor completely wrong. Will commit more pages regardless if they pretty or not

### CODE REVIEW

**Comment by d-huliu** [comment]
The subtitle and video "editor" section is basically an empty component with text, as I don't understand how an editor actually works. I'm assume the additional page UI are also to be added AFTER the page becomes somewhat functional. for example, after downloading the yt video, more components and buttons will appear, but the functionality needs to exist first.

**Comment by Vicopem01** [comment]
@d-huliu there is no way to access the pages

**Comment by chandhuDev** [comment]
@Vicopem01 present it is through only the urls 😅!

**Comment by Vicopem01** [comment]
but each page already has a component to route to it.

let's use the button on the home page as links instead

**Comment by chandhuDev** [comment]
How about having a nav section on the header bar to navigate to other pages !

As it stays for every page

**Comment by Vicopem01** [comment]
yes, we can ask david  for this

**Comment by Vicopem01** [comment]
but lets's still route the buttons to the pages, the buttons do not do anything right now

**Comment by chandhuDev** [comment]
@Vicopem01 how it is now?

**Comment by d-huliu** [comment]
> How about having a nav section on the header bar to navigate to other pages !
> 
> As it stays for every page

didn't victor want the icons on the landing page, to redirect to the pages. like, you click the icon, and then you will be taken to the page? or create a navbar.

**Comment by d-huliu** [comment]
> yes, we can ask david for this

need to add navbar now? like on the left hand side of the screen, just like aviewint website

**Comment by chandhuDev** [comment]
@d-huliu don't commit uncompleted code and please run it once locally before pushing the code.

Sidebar is not present on 3 pages and not aligned properly in other 2 pages

**Comment by d-huliu** [comment]
> @d-huliu don't commit uncompleted code and please run it once locally before pushing the code.
> 
> Sidebar is not present on 3 pages and not aligned properly in other 2 pages

I'm not sure what you mean by alignment. But yea I forgot to load it in the other pages

**Comment by Vicopem01** [comment]
Screenshot 2024-08-20 at 1 03 27 AM

@d-huliu 
### in the image above, these are the following to be fixed

- [x] the font size should be 16px if not specified in the design
- [x] add a trash icon that shows when a video is attached to be able to remove the video
- [x] remove the video timeline element on the bottom bar
- [x] remove the keyword **Project Name** for now
- [x] fix overflow issues in smaller screens
- [x] add drag and drop feature too for upload

**Comment by Vicopem01** [comment]
Screenshot 2024-08-20 at 1 11 08 AM

## for the image above, @d-huliu 
- [x] remove on logo from the sidebar
- [x] capitalize the first letter
- [x] use better page names
- [x] make it mobile responsive

**Comment by Vicopem01** [comment]
@chandhuDev @d-huliu any tasks completed from the list above should be checked so we can know how far we've gone

**Pull request merged**
